name: flutter_adv
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  retrofit: ^4.0.1
  analyzer: ^5.11.1
  dio: ^5.1.1
  json_serializable: ^6.6.2
  dartz: ^0.10.1

  flutter_native_splash: ^2.2.19
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ED9728"
  background_image: "assets/images/splash_logo.png"
  image: "assets/images/splash_logo"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.3.3



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
