name: flutter_adv
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  retrofit: ^3.0.1+1
  analyzer: ^3.3.1
  dio: ^4.0.4
  json_serializable: ^6.1.4
  dartz: ^0.10.1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.13
  freezed: ^1.1.1


  flutter_native_splash: ^2.2.19
  internet_connection_checker: ^0.0.1+3
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ED9728"
  background_image: "assets/images/splash_logo.png"
  image: "assets/images/splash_logo"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
